### ISSUE TITLE
CoroUtilCompatibility Console/Log Spam

### ISSUE THREAD

**Issue by Jizanthapus** [Corosauce/CoroUtil#21] opened 2018-02-04 01:17 UTC
`[20:05:00] [Server thread/INFO] [STDERR]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: java.lang.ClassNotFoundException: toughasnails.season.SeasonASMHelper`

I've been seeing a lot of output like that right after the world loads on my server.

[More output here](https://gist.github.com/Jizanthapus/d30321cb410170b45caab00cab2b13a1)

**Comment by s08171** [comment] 2018-02-18 18:31
I'm seeing the exact same thing.

**Comment by CDAGaming** [comment] 2018-02-23 12:47
Seeing this same thing also, @Corosauce Any fix in sight for this?

**Comment by Brittank88** [comment] 2018-03-22 01:17
Bump, also having this issue. Could be the possible cause why most of the time I crash when joining my own server.

**Comment by CDAGaming** [comment] 2018-03-22 01:25
@Brittank88 Whats your crash log? or what error does it give on disconnect...

**Comment by Brittank88** [comment] 2018-03-22 01:26
I will give what I can in a moment but the issue is... there is none. Not on server nor client. it just says I disconnected for the server logs, and for the client literally no errors at all. I'll send the files or in a pastebin shortly.

**Comment by CDAGaming** [comment] 2018-03-22 01:31
For me, it does the same in server, but in the client it gives "An existing connection was forcibly closed by the remote host."

**Comment by Brittank88** [comment] 2018-03-22 01:35
Oh my gosh, one of my client fml logs is nearly 10GB. I'm in the process of uploading to google drive now.

**Comment by Brittank88** [comment] 2018-03-22 09:25
@CDAGaming Sorry for being so late in actually posting the link to the logs, but here it is:
https://drive.google.com/open?id=1SEsRdtkFX68Y--sQeqiQcWrtnaoVGgPW

As you can see if you find a text editor capable of opening very large text files, the client log just... ends.
The last line states that it is joining the server on it's IP and then... nothing.

Anyway, I'm going through and re-adding the mods bit by bit to determine what the problem file is.

**Comment by Corosauce** [comment] 2018-04-28 20:55
Catching up on backlog, had this fixed a while ago, all should be good now.

**Closed by Corosauce** 2018-04-28 20:55 UTC
